# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{robot_enumerable}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Judge"]
  s.date = %q{2010-09-29}
  s.description = %q{robot_enumerable is a collection useful additions to the Array and Hash classes like #dupes?, #dupes_by, #uniq_by, #bump_to_front, and others. }
  s.email = %q{mikelovesrobots@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/robot_array.rb",
     "lib/robot_enumerable.rb",
     "robot_enumerable.gemspec",
     "test/helper.rb",
     "test/test_robot_enumerable.rb"
  ]
  s.homepage = %q{http://github.com/mikelovesrobots/robot_enumerable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{useful additions to the Array and Hash classes}
  s.test_files = [
    "test/helper.rb",
     "test/test_robot_enumerable.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

